### ISSUE TITLE
should be able to remove the code when changing a date

### ISSUE THREAD

**Issue by mecathcart** [cesine/fantastic-lamp#121]
**Describe the bug**
should be able to remove the code when changing a date

**To Reproduce**

1. make a encrypted message
2. Click on the calendar
3. choose any date
4. you will only get the encrypted message

**Expected behavior**
you should be able to navigate from an encrypted message to a previous cryptogram.

**Comment by cesine** [comment]
deploeyd in https://github.com/cesine/fantastic-lamp/compare/960007afb10012148c8bc4f2e9e99c48d0d1ee5d...main

<img width="1833" alt="Screenshot 2024-03-25 at 11 13 25 PM" src="https://github.com/cesine/fantastic-lamp/assets/196199/3de18b7f-153d-4d16-8f05-2a723bddb0c6">
<img width="1889" alt="Screenshot 2024-03-25 at 11 13 35 PM" src="https://github.com/cesine/fantastic-lamp/assets/196199/ff6b5cf9-5d85-4bac-b70c-75059038cf48">
