### ISSUE TITLE
Generate the share code without using the same cipher

### ISSUE THREAD

**Issue by mecathcart** [cesine/fantastic-lamp#122]
**Describe the bug**
generate a bunch of share codes wth the same cipher

**To Reproduce**

1. make a share code
2. make another share code
3. ciphers will be the same

**Expected behavior**
the ciphers should be distinct

**Screenshots**
Please see St. Patrick's Day Solve-along spreadsheet for examples.

**Comment by cesine** [comment]
fixed for solvalongs in #143
