### ISSUE TITLE
hard mode description is wrong

### ISSUE THREAD

**Issue by mecathcart** [cesine/fantastic-lamp#123]
**Describe the bug**
Hard mode description currently says: 
Any revealed hints must be used in subsequent guesses

**To Reproduce**

1. Go to page
2. Click on settings
3. Read what it says for hard mode

**Expected behavior**
Hard mode does not show colors. Hard mode does not indicate whether your guess is correct or incorrect.

**Comment by cesine** [comment]
deployed in https://github.com/cesine/fantastic-lamp/compare/960007afb10012148c8bc4f2e9e99c48d0d1ee5d...main

although the extra quotes dont look very good

<img width="1252" alt="Screenshot 2024-03-25 at 11 14 29 PM" src="https://github.com/cesine/fantastic-lamp/assets/196199/7cfeb14d-c1fe-48d4-828e-c1f3a7e7f2af">
