### ISSUE TITLE
the cipher is not random enough

### ISSUE THREAD

**Issue by mecathcart** [cesine/fantastic-lamp#124]
**Describe the bug**
Cipher for feb 22 === feb 20

**To Reproduce**

1.go to cipher for feb 22
2. then go to cipher for feb 20
3. see that they are the same

**Expected behavior**
ciphers should be distinct

**Comment by cesine** [comment]
i cant reproduce this anymore

https://isabelleclueright.com/cryptogram/?beta=true&d=2024-02-22

<img width="1897" alt="Screenshot 2024-03-25 at 11 07 07 PM" src="https://github.com/cesine/fantastic-lamp/assets/196199/0848365d-0226-4a06-866a-fa9a79c75b92">

https://isabelleclueright.com/cryptogram/?beta=true&d=2024-02-20

<img width="1920" alt="Screenshot 2024-03-25 at 11 08 26 PM" src="https://github.com/cesine/fantastic-lamp/assets/196199/a8618e94-2eda-4b20-ae27-db4f62f7ab39">
