### ISSUE TITLE
Letter in cipher cannot equal itself

### ISSUE THREAD

**Issue by mecathcart** [cesine/fantastic-lamp#127]
**Describe the bug**
E=E on feb 22

**To Reproduce**

1. Go to feb 22
2. enter E for E

**Expected behavior**
True cryptogrammers consider that all letters are distinctly substituted and not allowed to be themselves. this can be a hint in harder cryptograms.

**Comment by cesine** [comment]
I think this is fixed in #146  

<img width="1508" alt="Screenshot 2024-03-25 at 11 17 14 PM" src="https://github.com/cesine/fantastic-lamp/assets/196199/a123be1c-e1ac-45b8-9bc1-784217b8eb72">
