### ISSUE TITLE
confused about indexing quotes

### ISSUE THREAD

**Issue by mecathcart** [cesine/fantastic-lamp#132]
**Describe the bug**
I just want to document this before I lose my notes.  I figured out to find the index of date I wanted it would be this:
 31 + 29 + 18 (jan feb and what we have of march) this is 77.  Anyways today's quote was on line 74, so it should have been number 73.  Todays quote should have been an Oprah Winfrey quote.  Anyways,  I found today's quote, and stuck the quotes right after todays so that they would appear tomorrow.  But then when I ran the local host, we have a complete different quote for today, index 65.

**Comment by cesine** [comment]
fixed in #131
