### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by cesine** [cesine/fantastic-lamp#71]
**Is your feature request related to a problem? Please describe.**

As a project manager I want to know if users are using the app and which features they use the most/least

As a developer I want to know if users are having slow connections to vercel due to their ISP or due to throttling

**Describe the solution you'd like**

Install google analytics

~Install vercel analytics~

https://vercel.com/cesine/fantastic-lamp/analytics?environment=all

~Install vercel speed-insights~

https://vercel.com/cesine/fantastic-lamp/speed-insights

**Describe alternatives you've considered**

**Additional context**

**Comment by mecathcart** [comment]
we're not using vercel

**Comment by cesine** [comment]
Confirmed working
