### ISSUE TITLE
Refreshing

### ISSUE THREAD

**Issue by mecathcart** [cesine/fantastic-lamp#74]
**Describe the bug**
I had solved a cryptogram, then I refreshed the page and all the letters jumbled.
**To Reproduce**

1. go to the vercel app
2.partially solve the cryptogram
3. refresh the page
4. all the letters you put in will turn into different letters

**Expected behavior**
the letters should stay the same 

![Screen Shot 2024-03-03 at 3 09 20 PM](https://github.com/cesine/fantastic-lamp/assets/1167732/04eb950e-24fe-4e65-9179-eaac4ad5de67)

**Comment by cesine** [comment]
@mecathcart when you have time please verify that this is now working after I merged and deployed #80

**Comment by cesine** [comment]
we tested this today, it was working much better
